### ISSUE TITLE
loops run simultaneously?

### ISSUE THREAD

**Issue by pedrodude** [jowood4/RHINESTONE#2]
void MODE_NORMAL() I'm a little unclear on the execution order, do the for loops go sequentially or simultaneously?

**Comment by jowood4** [comment]
The loops will run sequentially.   I haven't worked out the flow completely
yet.  Arduino code must always have a setup function that runs at the
beginning of execution and a loop function that continuously cycles.  I'm
working on mapping your flow and functions to that Arduino framework.
